# Generated by Django 4.2.7 on 2025-12-09 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(default=list, help_text='List of amenities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='housing/')),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Housing Options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, help_text="e.g., '30 days', '90 days'", max_length=100)),
                ('features', models.JSONField(default=list, help_text='List of program features')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_location', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_approved', models.BooleanField(default=False, help_text='Approve for public display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='2nd Chance Recovery', max_length=200)),
                ('primary_color', models.CharField(default='#000000', help_text='Hex color code (Black)', max_length=7)),
                ('secondary_color', models.CharField(default='#808080', help_text='Hex color code (Gray)', max_length=7)),
                ('accent_color', models.CharField(default='#DC143C', help_text='Hex color code (Red)', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex color code (White)', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('hero_title', models.CharField(default='Your Journey to Recovery Starts Here', max_length=200)),
                ('hero_subtitle', models.TextField(default='Compassionate care for lasting recovery')),
                ('about_content', models.TextField(default='2nd Chance Recovery is dedicated to helping individuals overcome addiction and build a foundation for lasting recovery.')),
                ('contact_email', models.EmailField(default='info@2ndchancerecovery.com', max_length=254)),
                ('contact_phone', models.CharField(default='(555) 123-4567', max_length=20)),
                ('address', models.TextField(default='123 Recovery Street, City, State 12345')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
