# Generated by Django 4.2.7 on 2025-12-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn page URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', max_length=500, null=True),
        ),
    ]
