# Generated by Django 4.2.7 on 2025-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description of the wish list', max_length=200)),
                ('url', models.URLField(help_text='Full Amazon wish list URL', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Amazon Wish Lists',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Donor name (can be anonymous)', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Donation amount (optional)', max_digits=10, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor name')),
                ('is_featured', models.BooleanField(default=True, help_text='Show in news feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
