# Generated by Django 4.2.7 on 2025-12-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_amazonwishlist_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True)),
                ('reason_for_applying', models.TextField(help_text='Why are you applying for housing?')),
                ('special_needs', models.TextField(blank=True, help_text='Any special needs or accommodations required')),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('income_source', models.CharField(blank=True, max_length=200)),
                ('previous_treatment', models.TextField(blank=True, help_text='Previous treatment history')),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('denied', 'Denied'), ('waitlisted', 'Waitlisted')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('preferred_housing', models.ForeignKey(blank=True, help_text='Preferred housing option', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.housing')),
            ],
            options={
                'verbose_name_plural': 'Housing Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
