# Generated by Django 4.2.7 on 2026-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_housingapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(default='Our mission is to provide compassionate, evidence-based recovery services that empower individuals to overcome addiction and build a foundation for lasting sobriety.', help_text='Organization mission statement'),
        ),
    ]
