# Generated by Django 4.2.7 on 2026-01-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sitesettings_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(default='Recovery is dedicated to helping individuals overcome addiction and build a foundation for lasting recovery.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Recovery', max_length=200),
        ),
    ]
