# Generated by Django 4.2.7 on 2026-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='empty_state_color',
            field=models.CharField(default='#C19569', help_text="Hex color code for empty state messages (e.g., 'No programs available')", max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#91B9C1', help_text='Hex color code (Light Blue-Teal)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#D8DDE1', help_text='Hex color code (Light Gray)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#91B9C1', help_text='Hex color code (Light Blue-Teal)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#C19569', help_text='Hex color code (Tan/Brown)', max_length=7),
        ),
    ]
